DSP_ENV_DOCKER_IMAGE_NAME:              "dsp-env-img"
DSP_ENV_DOCKER_CONTAINER_NAME:          "dsp-env-container"

DSP_ENV_PATH_TO_HEXAGON_SDK_ROOT:       "/home/mfandakov/SDK/hexagon5.x/5.5.5.0"

# Has to have a filename as a basename
DSP_ENV_AARCH64_CROSS_COMPILER_URL:     "https://developer.arm.com/-/media/Files/downloads/\
                                         gnu-a/9.2-2019.12/binrel/\
                                         gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz"

# Has to have a filename as a basename
DSP_ENV_AARCH64_CROSS_COMPILER_ASC_URL: "https://developer.arm.com/-/media/Files/downloads/\
                                         gnu-a/9.2-2019.12/binrel/\
                                         gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz.asc"
                                         
# Has to have a filename as a basename
DSP_ENV_SAMPLE_MEMCPY_REPO_SSH_URL: "git@github.com:azimuth-m/DiplomnaMag-DSP-Environment-SampleDSPMemcpy.git"
